# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 天行健，君子以自强不息。 # ex. I m Chuan
name: 张进步 # ex. DONGChuan
email: 
location: Shenzen, China # ex. Nice, France
company: 
company_url: 
github_url: https://github.com/whatilove # ex. https://github.com/DONGChuan
github_username: # ex. DONGChuan
description: 
favicon: favicon.png # Image must be in assets/images
repository:  # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
# url: http://localhost:4000
 url: https://whatilove.github.io

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: whatilove # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: 首页

  # -
    # href: /notebook
    # label: 笔记本

 # -
   # href: /blog
   # label: Blog
  # -
    # href: /frontend
    # label: 前端

  -
    href: /about
    label: 关于我

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java]
skill_j2ee_keywords: [Struts2, SpringMVC, SpringBoot, SpringCloud, MyBatis, Redis]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, Vue, Vuex, Vue-Router, Boostrap]
skill_mobile_app_keywords: [Cordova]

permalink: /:year/:month/:day/:title
